# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildPortals
    displayName: Build Portals
    jobs:
      - job: build_publisher_portal
        displayName: 'Building Publisher'
        steps:
          - template: templates/install-nodejs.yaml
          - script: |
              cd portals/publisher/src/main/webapp && npm run build:prod
            displayName: '☢️ Building Publisher'
      - job: build_admin_portal
        displayName: 'Building Admin'
        steps:
          - template: templates/install-nodejs.yaml
          - script: |
              cd portals/admin/src/main/webapp && npm run build:prod
            displayName: '☢️ Building Admin'
      - job: build_devportal_portal
        displayName: 'Building Devportal'
        steps:
          - template: templates/install-nodejs.yaml
          - script: |
              cd portals/devportal/src/main/webapp && npm run build:prod
            displayName: '☢️ Building Devportal'

  - stage: UnitTests
    displayName: Test Portals
    jobs:
    - job: testing_library_tests
      displayName: Run unit tests (React Testing Library)
      timeoutInMinutes: '60'
      steps:
        - template: templates/install-nodejs.yaml
        - script: |
            cd portals/publisher/src/main/webapp && npm run test:ci
          displayName: '☢️ Testing (All Workspaces)'
        
        - task: PublishCodeCoverageResults@1 # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops
          inputs:
            codeCoverageTool: Cobertura
            summaryFileLocation: $(System.DefaultWorkingDirectory)/portals/**/coverage/cobertura-coverage.xml
            reportDirectory: '$(System.DefaultWorkingDirectory)/portals/**/coverage'